export enum MakamType {
    Rast = "Rast",
    Bayat = "Bayat",
    Nahawand = "Nahawand",
    Sikah = "Sikah",
    Hijaz = "Hijaz",
    Kurd = "Kurd",
    Ajam = "Ajam",
    Saba = "Saba",
    Hijazkar = "Hijazkar",
    Hijazkarkurdi = "Hijazkarkurdi",
    Nikriz = "Nikriz",
    NawAthar = "NawAthar",
    Rahawi = "Rahawi",
    ShatAraban = "ShatAraban",
    Zanjaran = "Zanjaran",
    Jaharka = "Jaharka",
}